### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### Profile
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im1hZ2EiLCJuYW1lIjoiTXVoYW1tYWR4b2phIiwibGFzdG5hbWUiOiJMdXRmdWxsYWV2IiwicGFzc3dvcmQiOiIxMjM0IiwicGhvbmVudW1iZXIiOiIrOTk4KDk5KTk4OC05OS01NiIsImltYWdlIjpudWxsLCJjcmVhdGVkQXQiOiIyMDIzLTAxLTA3VDEyOjAwOjU5LjQzOFoifSwiaWF0IjoxNjczMTA3NDI4LCJleHAiOjE2NzMxNDM0Mjh9.TbYM_XYaCFb04zr2ftSQf6P17hzk0Yf1t-KYogJvKpE
